crowdfunding/crowdfunding/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
#from user.views import views as u_views

urlpatterns = [
    path('admin/', admin.site.urls),
    #urls in main prject
    path('project/',include('project.urls')),
    path('', include("user.urls"))
    #path('user/',include('user.urls')),
    #urls not specific to a prticular app
    #path("home/", u_views.home),
    #path("login/", u_views.login),
    #path("register/", u_views.register),
    #path("logout/", u_views.logout),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crowdfunding/user/urls.py
from django.contrib import admin
from django.urls import path
from . import views




urlpatterns = [
    path("", views.index, name="index"),
    path("home/", views.index, name="home"),
    path("register/", views.register, name="register"),
    path("login/", views.login_user, name="login"),
    path("logout", views.logout_user, name="logout"),
    path("profile/edit", views.edit_profile, name="edit_profile"),
    path("profile/delete", views.delete_profile, name="delete_profile"),
    path("profile/<str:username>", views.profile, name="profile"),
    path("search/", views.search, name="search"),
    path("password_recovery/", views.password_recover, name="password_recover"),
]

crowdfunding/user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from project.models import Project

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=15)
    fb_profile_url = models.URLField(null=True, blank=True, max_length=200)
    country = models.CharField(default='Egypt', blank=True, null=True ,max_length=50)
    birth_date = models.DateField(null=True)
    profile_pic = models.ImageField(upload_to="profile_pics", default="profile_pics/default.jpg")

    '''
    Creating a signal so when an instance of User is being saved into DB an instance of UserProfile will be created and
    associated with the created User Instance and then save the profile instance.'''


    def get_all_projects(self):
        return self.project_set.all()

    def __str__(self):
        return self.user.username



class Comment (models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    date = models.DateField( auto_now_add=True)
    content = models.TextField()

    def __str__(self):
        return str(self.user_id) + " commented on " + str(self.project_id)



class Report (models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    def __str__(self):
        return self.user_id + " reported " + self.project_id

crowdfunding/user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
import re

def validate_egyptian_phone(value):
    if re.search(r"^01[0-25][\d]{8}$", value) is None:
        raise ValidationError("Not valid Phone Number.")
    return value


class RegisterationForm(UserCreationForm):
    phone = forms.CharField(max_length=15, required=True, validators=[validate_egyptian_phone])
    profile_pic = forms.ImageField(required=False)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )
    
class EditeProfileForm(forms.Form):
    username = forms.CharField(max_length=15, required=True)
    first_name = forms.CharField(max_length=15, required=True)
    last_name = forms.CharField(max_length=15, required=True)
    phone = forms.CharField(max_length=15, required=True, validators=[validate_egyptian_phone])
    profile_pic = forms.ImageField(required=False)
    fb_profile_url = forms.URLField(required=False, max_length=200)
    country = forms.CharField(max_length=15, required=False)
    birth_date = forms.DateField(required=False)

"""     class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name',)
        exclude = ("password1", "password2") """
    
class ProfileForm(UserCreationForm):
    pass

crowdfunding/user/views.py
from django.shortcuts import render, reverse, redirect
from django.contrib.auth import login, logout, authenticate 
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from project import models as p_models
from .models import UserProfile
from .forms import RegisterationForm, EditeProfileForm
import re
from django.db.models import Q
from .utils import get_random_password


def index(request):
    context = {
        "top_rated_five": p_models.Project.get_top_five_rated(),
        "last_created_five": p_models.Project.get_last_five_created(),
        "recommended_five": p_models.Project.get_most_recommended_five(),
        "categories": p_models.Category.objects.all()
    }
    return render(request, "user/home.html", context)


def register(request):
    if request.method == 'POST':
        form = RegisterationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            #user.refresh_from_db()  #load the profile instance created by the signal
            profile = UserProfile.objects.create(user=user)
            profile.phone = form.cleaned_data.get("phone")
            if form.cleaned_data.get("profile_pic"):
                profile.profile_pic = form.cleaned_data.get("profile_pic")
            user.userprofile.save()
            password = form.cleaned_data.get("password1")
            user = authenticate(username=user.username, password=password)
            if user:
                login(request, user)
                return redirect(reverse("home"))
            return render(request, "user/login.html", {'form': form, "categories": p_models.Category.objects.all()})
        else:
            return render(request, "user/register.html", {'form': form, "categories": p_models.Category.objects.all()})
    else:
        form = RegisterationForm()
    return render(request, 'user/register.html', {'form': form, "categories": p_models.Category.objects.all()})


def login_user(request):
    if request.method == "POST":
        #if request.user.is_a
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(username=username, password=password)
        if user:
            login(request, user)
            return redirect(reverse("home"))
        return render(request, "user/login.html", {"categories": p_models.Category.objects.all()})
    else:
        return render(request, "user/login.html", {"categories": p_models.Category.objects.all()})


@login_required(login_url='/login')
def logout_user(request):
    logout(request)
    return redirect(reverse("index"))


def profile(request, username):
    user = User.objects.get(username=username)
    projects = [
        {"project_obj" : project, "header_image": project.get_header_image()} for project in user.project_set.all()
    ]
    context = {
        "profile_user_name": user.first_name + " " + user.last_name,
        "user": user,
        "profile": user.userprofile,
        "date_joined": user.date_joined.date(),
        "projects": projects,
        "donations": user.donation_set.all(),
        "categories": p_models.Category.objects.all(),
        "form": EditeProfileForm()
    }
    return render(request, "user/profile.html", context)


@login_required(login_url="/login")
def delete_profile(request):
    user = request.user
    logout(request)
    user.delete()
    return redirect(reverse("index"))


@login_required(login_url="/login")
def edit_profile(request):
    if request.method == 'POST':
        print(request.FILES)
        form = EditeProfileForm(request.POST, request.FILES)
        if form.is_valid():
            #user = form.save()
            #print(user)
            #user.refresh_from_db()  #load the profile instance created by the signal
            profile = request.user.userprofile#UserProfile.objects.create(user=user)
            profile.phone = form.cleaned_data.get("phone")
            if form.cleaned_data.get("profile_pic"):
                profile.profile_pic = form.cleaned_data.get("profile_pic")
            request.user.userprofile.save()
            request.user.username = form.cleaned_data.get("username")
            request.user.first_name = form.cleaned_data.get("first_name")
            request.user.last_name = form.cleaned_data.get("last_name")
            request.user.save()

            return render(request, "user/profile.html", {'form': form, "categories": p_models.Category.objects.all()})
        else:
            print(form.errors)
            return redirect(reverse("profile", kwargs={
                "username": request.user.username}))
        return redirect(reverse("profile", kwargs={
            "username": request.user.username}))
    else :
        return render(request, "user/edit_profile.html", {user: request.user})
        
    

def search(request):
    query_param = request.GET.get("q")
    if query_param:
        #get the projects with title matches the search string excluding the tags (strings prefixed with #).
        parsed_query = "".join(re.split("#\w+", query_param))
        projects_contains_titles = p_models.Project.objects.filter(title__icontains=parsed_query)
        #get all tags and get all projects the have either on of those tags
        tags = re.findall("#(\w+)", query_param)
        projects_contains_tags = []
        if tags:
            q = Q(tags__name__icontains = tags[0])
            for tag in tags[1:]:
                q |= Q(tags__name__icontains=tag)
            projects_contains_tags = p_models.Project.objects.filter(q).distinct()
        projects = set(list(projects_contains_tags) + list(projects_contains_titles))
        for project in projects:
            project.header_img = project.get_header_image()
            project.rate = project.get_avg_rate()
        #return a unique set of all projects
        context = {
            "projects": projects,
            "categories": p_models.Category.objects.all()
        }
        return render(request, 'project/results.html', context)

def password_recover(request):
    ''' Don't touch this it's not working '''
    if request.method == "POST":
        try: 
            from django.core.mail import send_mail
        except ImportError:
            return redirect(reverse("index"), message="Failed to send email.")
        username = request.POST.get("username")
        new_password = get_random_password(30)
        User.objects.get(username=username).set_password(password)
        send_mail(
            'Password Reset',
            'Here is the message.',
            'from@example.com',
            ['to@example.com'],
            fail_silently=False,
        )
        return redirect()
    return render(request, "user/password_reset_confirm.html")

crowdfunding/user/templates/user/_edit_profile_form.html
<button type="button" class="btn btn-sm btn-block btn-success" data-toggle="modal" data-target="#edit-profile-modal">
  <i class="ace-icon fa fa-plus-circle bigger-120"></i>
  <span class="bigger-110">edite</span>
</button>

<div class="modal fade" id="edit-profile-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Profile</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method="POST" action="{% url 'edit_profile' %}" enctype="multipart/form-data">
        <div class="modal-body">
            {% csrf_token %}
              <div class="form-group">
                <label for="id_first_name">Username:</label>
                <input type="text" name="username" maxlength="30" id="id_username" class="form-control" value="{{ user.username }}">
              </div>
              <div class="form-group">
                <label for="id_first_name">First name:</label>
                <input type="text" name="first_name" maxlength="30" id="id_first_name" class="form-control" value="{{ user.first_name }}">
              </div>
              <div class="form-group">
                <label for="id_last_name">Last name:</label>
                <input type="text" name="last_name" maxlength="30" id="id_last_name" class="form-control" value="{{ user.last_name }}">
              </div>
              <div class="form-group">
                <label for="id_phone">Phone:</label>
                <input type="text" name="phone" maxlength="15" id="id_phone" class="form-control" value="{{ profile.phone }}">
              </div>
              <div class="form-group">
                <label for="id_profile_pic">Profile pic:</label>
                <input type="file" name="profile_pic" accept="image/*" id="id_profile_pic" class="form-control" value="{{ profile.profile_pic }}">
              </div>
              <div class="form-group">
                <label for="id_fb_profile_url">Fb profile url:</label>
                {% if profile.fb_profile_url %}
                <input type="url" name="fb_profile_url" maxlength="200" id="id_fb_profile_url" class="form-control" value="{{ profile.fb_profile_url }}">
                {% else %}

                <input type="url" name="fb_profile_url" maxlength="200" id="id_fb_profile_url" class="form-control" value="">
                {% endif%}
              </div>
              <div class="form-group">
                <label for="id_country">Country:</label>
                <input type="text" name="country" maxlength="15" id="id_country" class="form-control" value="{{ profile.country }}">
              </div>
              <div class="form-group">
                <label for="id_birth_date">Birth date:</label>
                 {% if profile.fb_profile_url %}
                <input type="url" name="birth_date" maxlength="200" id="id_birth_date" class="form-control" value="{{ profile.birth_date }}">
                {% else %}

                <input type="url" name="birth_date" maxlength="200" id="id_birth_date" class="form-control" value="">
                {% endif %}
              </div>
  
        </div>
        <div class="modal-footer">
          <button type="submit" class="btn btn-primary">Save changes</button>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </form>
    </div>
  </div>
</div>

crowdfunding/user/templates/user/_login_form.html
<form action="{% url 'login' %}" method="POST">
    {% csrf_token %}
    <p class="hint-text">Sign in with your social media account</p>
    <div class="form-group social-btn clearfix">
        <a href="#" class="btn btn-primary pull-left"><i class="fa fa-facebook"></i> Facebook</a>
        <a href="#" class="btn btn-info pull-right"><i class="fa fa-twitter"></i> Twitter</a>
    </div>
    <div class="or-seperator"><b>or</b></div>
    <div class="form-group">
        <input type="text" class="form-control" placeholder="Username" required name="username">
    </div>
    <div class="form-group">
        <input type="password" class="form-control" placeholder="Password" required name="password">
    </div>
    <input type="submit" class="btn btn-primary btn-block" value="Login">
    <div class="form-footer">
        <a href="{% url 'password_recover' %}">Forgot Your password?</a>
    </div>
</form>

crowdfunding/user/templates/user/_navbar.html
<nav class="navbar navbar-expand-lg sticky-top navbar-light bg-light mb-4">
    <a class="navbar-brand" href="{% url 'home'%}">CrowdFunding</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'add_project' %}">Add Project</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="categoriesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Categories
                </a>
                <div class="dropdown-menu" aria-labelledby="categoriesDropdown">
                    {% for category in categories %}
                        <a class="dropdown-item" href="{% url 'category_project' category.name %}">{{ category.name }}</a>
                    {% endfor %}
                </div>
            </li>
        </ul>
        <form class="navbar-form form-inline my-2" method="GET" action="{% url 'search' %}">
		<div class="input-group search-box">								
				<input type="text" id="search" class="form-control" placeholder="Search here..." name="q">
				<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
			</div>
        </form>
    <ul class="nav navbar-nav navbar-right ml-auto">			
	    
        {% if request.user.is_authenticated %}  
            <li class="nav-item dropdown">
				<a data-toggle="dropdown" class="nav-link dropdown-toggle" href="#">
                    <img src="{{ request.user.userprofile.profile_pic.url }}" class="rounded-circle"></a>
                </a>
				<div class="dropdown-menu profile-actions">					
					<a href="{% url 'profile' request.user.username %}" class="dropdown-item center">Profile</a>
                    <a href="{% url 'edit_profile' %}" class="dropdown-item center">Edite</a>
                    <a id ="delete-btn" href="{% url 'delete_profile' %}" class="dropdown-item center">Delete</a>
                    <a href="{% url 'logout' %}" class="dropdown-item center">Logout</a>
				</div>
			</li>
        {% else %}
            <li class="nav-item">
				<a data-toggle="dropdown" class="nav-link dropdown-toggle" href="#">Login</a>
				<ul class="dropdown-menu form-wrapper">					
					<li>
						{% include 'user/_login_form.html' %}
					</li>
				</ul>
			</li>
			<li class="nav-item">
				<a href="{% url 'register' %}"  class="btn btn-primary dropdown-toggle get-started-btn mt-1 mb-1">Sign up</a>
			</li>
        {% endif %}
	</ul>

    </div>
</nav>

crowdfunding/user/templates/user/edit_profile.html
{% extends 'user/layout.html' %}

{% block content %}
    <h2>Edit</h2>
          <form method="POST" action="{% url 'edit_profile' %}" enctype="multipart/form-data">
        <div class="modal-body">
            {% csrf_token %}
              <div class="form-group">
                <label for="id_first_name">Username:</label>
                <input type="text" name="username" maxlength="30" id="id_username" class="form-control" value="{{ user.username }}">
              </div>
              <div class="form-group">
                <label for="id_first_name">First name:</label>
                <input type="text" name="first_name" maxlength="30" id="id_first_name" class="form-control" value="{{ user.first_name }}">
              </div>
              <div class="form-group">
                <label for="id_last_name">Last name:</label>
                <input type="text" name="last_name" maxlength="30" id="id_last_name" class="form-control" value="{{ user.last_name }}">
              </div>
              <div class="form-group">
                <label for="id_phone">Phone:</label>
                <input type="text" name="phone" maxlength="15" id="id_phone" class="form-control" value="{{ profile.phone }}">
              </div>
              <div class="form-group">
                <label for="id_profile_pic">Profile pic:</label>
                <input type="file" name="profile_pic" accept="image/*" id="id_profile_pic" class="form-control" value="{{ profile.profile_pic }}">
              </div>
              <div class="form-group">
                <label for="id_fb_profile_url">Fb profile url:</label>
                {% if profile.fb_profile_url %}
                <input type="url" name="fb_profile_url" maxlength="200" id="id_fb_profile_url" class="form-control" value="{{ profile.fb_profile_url }}">
                {% else %}

                <input type="url" name="fb_profile_url" maxlength="200" id="id_fb_profile_url" class="form-control" value="">
                {% endif%}
              </div>
              <div class="form-group">
                <label for="id_country">Country:</label>
                <input type="text" name="country" maxlength="15" id="id_country" class="form-control" value="{{ profile.country }}">
              </div>
              <div class="form-group">
                <label for="id_birth_date">Birth date:</label>
                 {% if profile.fb_profile_url %}
                <input type="url" name="birth_date" maxlength="200" id="id_birth_date" class="form-control" value="{{ profile.birth_date }}">
                {% else %}

                <input type="url" name="birth_date" maxlength="200" id="id_birth_date" class="form-control" value="">
                {% endif %}
              </div>
  
        </div>
        <div class="modal-footer">
          <button type="submit" class="btn btn-primary">Save changes</button>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </form>
{% endblock %}

crowdfunding/user/templates/user/home.html
{% extends 'user/layout.html' %}
{% block content %}
<!-- Heighest rated five -->

<div class="row justify-content-center">
    <h1 class="my-4 ">Top rated Projects</h1>
</div>
<div class="row justify-content-center my-4">
    <div class="col-10">
        <div id="carousalID" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousalID" data-slide-to="0" class="active"></li>
                <li data-target="#carousalID" data-slide-to="1"></li>
                <li data-target="#carousalID" data-slide-to="2"></li>
                <li data-target="#carousalID" data-slide-to="3"></li>
                <li data-target="#carousalID" data-slide-to="4"></li>
            </ol>
            <div class="carousel-inner">
                {% for project in top_rated_five %}
                    {% if forloop.counter0 == 0 %}
                        <div class="carousel-item active">
                    {% else %}
                        <div class="carousel-item">
                    {% endif %}
                            <a href="{% url 'project' project.project_id %}"><img class="d-block w-100" src="{{ project.header_image }}" alt="" width="100%" height="400px"></a>
                            <div class="carousel-caption d-none d-md-block">
                                <h3 class="text-uppercase">{{ project.project_title }}</h3>
                                <p>Rated {{ project.project_rate }}/5 ({{ project.num_rates}})
                                </p>

                            </div>
                        </div>
                {% endfor %}
            </div>
            <a class="carousel-control-prev" href="#carousalID" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carousalID" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
</div>

<!-- Last created five -->
<div class="row justify-content-center">
    <h1 class="my-4 ">Lastly Added Projects</h1>
</div>
<div class="card-group my-4">
    {% for project in last_created_five %}
        <div class="card">
            <a href="{% url 'project' project.project_id %}"><img src="{{ project.header_image }}" class="card-img-top" alt="" height="200px" width="300px"></a>
            <div class="card-body">
                <a href="{% url 'project' project.project_id %}"><h5 class="card-title">{{ project.project_title}}</h5></a>
                <p class="card-text">Rated {{ project.project_rate}}/5 ({{ project.num_rates}})</p> 
                <p>Target: {{ project.target }}</p>
                <p>Gain: {{ project.percentage }}%</p>
            </div>
            <div class="card-footer">
            <small class="text-muted">Created at {{ project.creation_date}}</small>
            </div>
        </div>
    {% endfor %}
</div>

<!-- recommended five -->
<div class="row justify-content-center">
    <h1 class="my-4 ">Recommended for you</h1>
</div>
<div class="card-group my-4">
    {% for project in recommended_five %}
        <div class="card">
            <a href="{% url 'project' project.project_id %}"><img src="{{ project.header_image }}" class="card-img-top" alt="" height="200px" width="300px"></a>
            <div class="card-body">
                <a href="{% url 'project' project.project_id %}"><h5 class="card-title">{{ project.project_title}}</h5></a>
                <p class="card-text">Rated {{ project.project_rate}}/5 ({{ project.num_rates}})</p>
                <p>Target: {{ project.target }}</p>
                <p>Gained: {{ project.percentage }}%</p>
            </div>
            <div class="card-footer">
            <small class="text-muted">Created at {{ project.creation_date}}</small>
            </div>
        </div>
    {% endfor %}
</div>

<div style="height:1000px"></div>
{% endblock content %}

crowdfunding/user/templates/user/layout.html
{% load static %}

<html>
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Crowdfunding</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">

        <link rel="stylesheet" href="{% static 'styles/starrr.css' %}">
        <link rel="stylesheet" href="{% static 'styles/tagify.css' %}">
        <link rel="stylesheet" href="{% static 'styles/style.css' %}">
        <script src="{% static 'js/jQuery.tagify.min.js' %}"></script>
        <script src="{% static 'js/starrr.js' %}"></script>
    </head>
    <body>
        <div class="container">

        
        {% include "user/_navbar.html" %}

        {% if messages %}
            {% for message in messages %}
                <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %} alert-dismissible fade show" role="alert">{{ message }}</div>
            {% endfor %}
        {% endif %}

        {% block content %}
        {% endblock content %}
        </div>
    </body>
    <script type="text/javascript">
        // Prevent dropdown menu from closing when click inside the form
        $(document).on("click", ".navbar-right .dropdown-menu", function(e){
            e.stopPropagation();
        });
        $("#tab-bar li").on('click', function(){
            $("#tab-bar li.active").removeClass("active");
            $(this).addClass("active");
        });

        //Confirm on deleteing account
        $("#delete-btn").confirm({
            title: 'Confirm!',
            content: 'Are you sure you want to delete your acount!',
        });

    </script>

</html>

crowdfunding/user/templates/user/login.html
{% extends 'user/layout.html' %}

{% block content %}
    <h2>Sign In</h2>
    {% include 'user/_login_form.html' %}
{% endblock %}

crowdfunding/user/templates/user/password_reset_confirm.html
{% extends 'user/layout.html' %}

{% block content %}

<form action="{% url 'password_recovery' %}" method="POST">
    {% csrf_token %}
    <p class="hint-text">Enter Your username</p>
    <div class="form-group">
        <input type="text" class="form-control" placeholder="Username" required name="username">
    </div>
    <input type="submit" class="btn btn-primary btn-block" value="Send">
</form>
{% endblock content %}

crowdfunding/user/templates/user/register.html
{% extends 'user/layout.html' %}

{% block content %}
  <h2>Sign up</h2>
  <form method="POST" action="{% url 'register' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}